version: "3"
services:
  plug-dj-client:
    image: plug-dj-client
    build: .
    env_file: 
        - .env
    environment:
      - PUPPETEER_CONTAINED=true
      - REDIS_HOST=redis
  redis:
    image: redis:latest
