version: "3"
services:
  plug-dj-client:
    image: plug-dj-client
    build: .
    environment:
      - REDIS_HOST=redis
      - PLUG_USERNAME=
      - PLUG_PASSWORD=
      - PLUG_ROOM=
  redis:
    image: redis:latest
