export default Object.freeze({
  ADVANCE: 'ADVANCE',
  CHAT: 'CHAT',
  CHAT_COMMAND: 'CHAT_COMMAND',
  FRIEND_JOIN: 'FRIEND_JOIN',
  GRAB_UPDATE: 'GRAB_UPDATE',
  HISTORY_UPDATE: 'HISTORY_UPDATE',
  MOD_SKIP: 'MOD_SKIP',
  SCORE_UPDATE: 'SCORE_UPDATE',
  USER_JOIN: 'USER_JOIN',
  USER_LEAVE: 'USER_LEAVE',
  USER_SKIP: 'USER_SKIP',
  VOTE_UPDATED: 'VOTE_UPDATED',
  WAIT_LIST_UPDATE: 'WAIT_LIST_UPDATE'
});
